---
title: "Plotting example"
author: "John Mount, Nina Zumel"
date: "January 10, 2018"
output: github_document
---

As a follow-up to ["rquery: Fast Data Manipulation in R"](http://www.win-vector.com/blog/2018/01/rquery-fast-data-manipulation-in-r/)
I re-ran the experiment with a nice "base R" implementation of the calculation
added to the assessments.  It turns out base R is much faster than any of the alternatives.

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(wrapr)
library(rquery)

source("../plotbenchmark.R")

timings = readRDS("qtimings.RDS")
timings$expr <- as.character(timings$expr)

# colors
highlightcolor = "#33a02c"
backgroundcolor = "#a6cee3"
reruncolor = "#b2df8a"
greycolor = "darkgrey"

```

```{r}



runs <- c("base R calculation",
          "data.table in memory", 
          "rquery in memory",
          "dplyr tbl in memory",
          "dplyr in memory no grouped filter",
          "dplyr from memory to db and back")
colormap = runs := c(highlightcolor,
                     highlightcolor,
                     highlightcolor,
                     highlightcolor,
                     highlightcolor,
                     backgroundcolor)

tr <- timings[timings$expr %in% runs, , drop=FALSE]
tr$expr <- factor(tr$expr, levels = rev(runs))
plotbenchmark(tr, colormap, 
              title = "In-Memory Runtimes by Implementation (smaller better)",
              subtitle = "Database enhanced dplyr shown for comparison")


summary <- tr %.>% 
  as.data.frame(.) %.>%
  project_nse(., "expr", durationMS = avg(time)/1000000 ) %.>%
  orderby(., "durationMS") %>%
  execute(.)
baseTiming <- summary$durationMS[[which(summary$expr == 
                                          "base R calculation")]]
summary$relativeDuration <- summary$durationMS / baseTiming

knitr::kable(summary)

```
