---
title: "yaml"
output: github_document
---

This is an example of `R` reading a `YAML` representation of a `Python` [`data_algebra`](https://github.com/WinVector/data_algebra) pipeline.  The example being read comes from [here](https://github.com/WinVector/data_algebra/blob/master/Examples/LogisticExample/ScoringExample.ipynb).

```{r}
library(yaml)
library(wrapr)
library(rquery)
library(rqdatatable)

rep <- yaml.load_file("pipeline_yaml.txt")


expr_map_to_expr_array <- function(emap) {
  r = vapply(names(emap), function(k) paste0(k, " := ", emap[[k]]), character(1))
  names(r) <- NULL
  return(r)
}

convert_yaml_to_pipleline <- function(rep, source=NULL) {
  if(is.null(names(rep))) {
    # unnamed list, a pipleline
    res <- convert_yaml_to_pipleline(rep[[1]])
    for(i in seqi(2, length(rep))) {
      res <- convert_yaml_to_pipleline(rep[[i]], source=res)
    }
    return(res)
  } else {
    # named list, a stage
    op = rep$op
    if(op=="TableDescription") {
      return(mk_td(table_name = rep$table_name,
                   columns = rep$column_names))
    } else if(op=="Extend") {
      return(extend_se(source, 
                       assignments = expr_map_to_expr_array(rep$ops),
                       partitionby = as.character(rep$partition_by),
                       orderby = as.character(rep$order_by),
                       reverse = as.character(rep$reverse)))
    } else if(op=="SelectRows") {
      return(select_rows_se(source,
                            expr = rep$expr))
    } else if(op=="SelectColumns") {
      return(select_columns(source, columns=rep$columns))
    } else if(op=="Rename") {
      return(rename_columns(source, cmap=rep$column_remapping))  # TODO: see if map is dumped (or __repr__() call wrote a string)
    } else if(op=="Order") {
      return(orderby(source, cols=rep$order_columns, reverse=rep$reverse, limit=rep$limit))
    } else {
      stop("Unexpected node type: " + op) 
    }
  }
} <- function(rep, source=NULL) {
  if(is.null(names(rep))) {
    # unnamed list, a pipleline
    res <- convert_yaml_to_pipleline(rep[[1]])
    for(i in seqi(2, length(res))) {
      res <- convert_yaml_to_pipleline(rep[[i]], source=res)
    }
    return(res)
  } else {
    # named list, a stage
    op = rep$op
    if(op=="TableDescription") {
      return(mk_td(table_name = rep$table_name,
                   columns = rep$column_names))
    } else if(op=="Extend") {
      return(extend_se(source, 
                       assignments = expr_map_to_expr_array(rep$ops),
                       partitionby = as.character(rep$partition_by),
                       orderby = as.character(rep$order_by),
                       reverse = as.character(rep$reverse)))
    } else if(op=="SelectRows") {
      return(select_rows_se(source,
                            expr = rep$expr))
    } else if(op=="SelectColumns") {
      return(select_columns(source, columns=rep$columns))
    } else if(op=="Rename") {
      return(rename_columns(source, cmap=rep$column_remapping))  # TODO: see if map is dumped (or __repr__() call wrote a string)
    } else if(op=="Order") {
      return(orderby(source, cols=rep$order_columns, reverse=rep$reverse, limit=rep$limit))
    } else {
      stop("Unexpected node type: " + op) 
    }
  }
}

ops <- convert_yaml_to_pipleline(rep)
cat(format(ops))

cat(to_sql(ops, rquery_default_db_info()))
```

```{r}
d_local <- build_frame(
   "subjectID", "surveyCategory"     , "assessmentTotal", "irrelevantCol1", "irrelevantCol2" |
   1L         , "withdrawal behavior", 5                , "irrel1"        , "irrel2"         |
   1L         , "positive re-framing", 2                , "irrel1"        , "irrel2"         |
   2L         , "withdrawal behavior", 3                , "irrel1"        , "irrel2"         |
   2L         , "positive re-framing", 4                , "irrel1"        , "irrel2"         )

d_local %.>% 
  ops %.>% 
  knitr::kable(.)
```


```{r diagram, fig.width=8, fig.height=8}
ops %.>%
  op_diagram(.) %.>% 
  DiagrammeR::grViz(.)
```
