---
title: "QTiming"
author: "Win-Vector LLC"
date: "1/7/2018"
output: github_document
---

```{r dbsetup}
library("rquery")
library("dplyr")
library("microbenchmark")
library("rbenchmark")
library("ggplot2")

db <- DBI::dbConnect(RPostgres::Postgres(),
                     host = 'localhost',
                     port = 5432,
                     user = 'postgres',
                     password = 'pg')
winvector_temp_db_handle <- list(db = db)
```


```{r data}
nrep <- 10000

dL <- data.frame(
  subjectID = c(1,                   
                1,
                2,                   
                2),
  surveyCategory = c(
    'withdrawal behavior',
    'positive re-framing',
    'withdrawal behavior',
    'positive re-framing'
  ),
  assessmentTotal = c(5,                 
                      2,
                      3,                  
                      4),
  irrelevantCol1 = "irrel1",
  irrelevantCol2 = "irrel2",
  stringsAsFactors = FALSE)
norig <- nrow(dL)
dL <- dL[rep(seq_len(norig), nrep), , drop=FALSE]
dL$subjectID <- paste((seq_len(nrow(dL)) -1)%/% norig,
                      dL$subjectID, 
                      sep = "_")
rownames(dL) <- NULL
head(dL)

dR <- rquery::dbi_copy_to(db, 'dR',
                  dL,
                  temporary = TRUE, 
                  overwrite = TRUE)
cdata::qlook(db, dR$table_name)

dT <- dplyr::tbl(db, dR$table_name)
dplyr::glimpse(dT)
```


```{r query}
scale <- 0.237

# this is a function, 
# so body not evaluated until used
rquery_pipeline <- . := {
  extend_nse(.,
             probability :=
               exp(assessmentTotal * scale)/
               sum(exp(assessmentTotal * scale)),
             count := count(1),
             partitionby = 'subjectID') %.>%
    extend_nse(.,
               rank := rank(),
               partitionby = 'subjectID',
               orderby = c('probability', 'surveyCategory'))  %.>%
    rename_columns(., 'diagnosis' := 'surveyCategory') %.>%
    select_rows_nse(., rank == count) %.>%
    select_columns(., c('subjectID', 
                        'diagnosis', 
                        'probability')) %.>%
    orderby(., 'subjectID') 
}



rquery_local <- function() {
 dL %.>% 
    rquery_pipeline %.>%
    as.data.frame(.) # force execution
}

rquery_database <- function() {
 dR %.>% 
    rquery_pipeline %.>% 
    to_sql(., db) %.>% 
    DBI::dbGetQuery(db, .) %.>%
    as.data.frame(.) # shouldn't be needed
}

# this is a function, 
# so body not evaluated until used
dplyr_pipeline <- . %>%
  group_by(subjectID) %>%
    mutate(probability =
             exp(assessmentTotal * scale)/
             sum(exp(assessmentTotal * scale)), na.rm = TRUE) %>%
    arrange(probability, surveyCategory) %>%
    filter(row_number() == n()) %>%
    ungroup() %>%
    rename(diagnosis = surveyCategory) %>%
    select(subjectID, diagnosis, probability) %>%
    arrange(subjectID)
  
dplyr_local <- function() {
  dL %>% 
    dplyr_pipeline
}

dplyr_database <- function() {
  dT %>% 
    dplyr_pipeline %>%
    collect()
}
```

```{r show}
head(rquery_local())

head(rquery_database())

head(dplyr_local())

head(dplyr_database())
```

I have tried to get rid of the warnings that
the dplyr database pipeline is producing, but adding the "`na.rm = TRUE`" appears to have no effect.



```{r timings, warning=FALSE}
# check from: 
# https://cran.r-project.org/web/packages/microbenchmark/microbenchmark.pdf
my_check <- function(values) {
  all(sapply(values[-1], 
             function(x) identical(values[[1]], x)))
}

tm <- microbenchmark(
  nrow(rquery_local()),
  nrow(rquery_database()),
  nrow(dplyr_local()),
  nrow(dplyr_database()),
  check=my_check)
print(tm)
autoplot(tm)
```

`rquery` appears to be fast.  The extra time for "`rquery` local" is because `rquery`
doesn't *really* have a local mode, it has to copy the data to the database and back
in that case.

```{r timingsr,  warning=FALSE}
tb <- benchmark(
  rquery_local = { nrow(rquery_local()) },
  rquery_database = { nrow(rquery_database()) },
  dplyr_local = { nrow(dplyr_local()) },
  dplyr_database = { nrow(dplyr_database()) }
)
knitr::kable(tb)
```

```{r dbcleanup}
winvector_temp_db_handle <- NULL
DBI::dbDisconnect(db)
```
